### ISSUE TITLE
Blobs

### ISSUE THREAD

**Issue by JoseSalvadorNeg** [DCIDA2019/dcida2020ii-JoseSalvadorNeg#1]
Al correr emcee, aparece el error "ValueError: If you start sampling with a given log_prob, you also need to provide the current list of blobs at that position."

Revisando la documentación de emcee, blobs hace referencia (por lo que entiendo) al guardado de los valores de prior y el likelihood, pero pareciera ser que el código no tiene nada diferente a comparación del código donde muestran como guardar dichos valores. Quisiera saber cómo arreglar dicho error.

**Comment by alxogm** [comment]
Creo que tu issue es en la celda 

```
In [137]:
pos = [0.3, 0.15, 3.0, -19.0, -0.0070] + 1e-4 * np.random.randn(10, 5)
nwalkers, ndim = pos.shape
```

de aquí: `https://github.com/DCIDA2019/dcida2020ii-JoseSalvadorNeg/blob/master/proyectofinal/proyecto_beta.ipynb
`
Por lo que veo el emcee si inicia y evoluciona y después de un tiempo es que te manda ese error. Eso me hace pensar que es un problema en el likelihood que quizá está dando un valor no aceptable, infinito, NAN o algo  así... lo que puedes hacer es imprimir los valores del likelihood a cada paso para intentar atrapar el error. Dado que mcmc si está avanzando me parece que puede ser algún problema así. 

Saludos

**Comment by JoseSalvadorNeg** [comment]
Me puse a imprimir los valores del likelihood y el resultado es que no encontré nada fuera de lo normal o común. Ya actualicé el archivo ubicado en https://github.com/DCIDA2019/dcida2020ii-JoseSalvadorNeg/blob/master/proyectofinal/proyecto_beta.ipynb y el último resultado antes de dar el mismo error fue -1038252.01544738. Estoy experimentando con cambiar la forma en la que tengo escritas algunas cosas en la función del likelihood con la esperanza de eliminar la fuente de error, pero no he podido aún.

**Comment by alxogm** [comment]
@JoseSalvadorNeg Ya le pedí a @HiramHerrera que le de un vistazo a tu código, si tengo oportunidad a lo largo del día puedo mirarlo también.

**Comment by HiramHerrera** [comment]
Hola @JoseSalvadorNeg , revisando tu código, creo que el problema está en la celda que defines tus priors, y en la que defines tus posiciones iniciales.

Para los priors tienes: 

```
def log_prior(theta):
    omega, alfa, beta, masa, delta = theta
    if 0.0 < omega < 1.0 and 0.0 < alfa < 1.0 and 3 < beta < 4 and -20 < masa < -19 and -1.0 < delta < 0.0:
        prior = 0
    else:
        prior = -np.inf
    return prior

```
Mientras que para tus posiciones iniciales tienes:

```
pos = [0.3, 0.15, 3.0, -19.0, -0.0070] + 1e-4 * np.random.randn(10, 5)
nwalkers, ndim = pos.shape

sampler = emcee.EnsembleSampler(nwalkers, ndim, log_probability)
pos,prob,state=sampler.run_mcmc(pos, 100, progress=True);
```

Los valores que das como base para iniciar beta y masa están en el borde de tus priors y es posible que algunos walkers inicien en valores iniciales fuera de este rango. Esto genera que tus walkers se queden estancados sin generar nuevos estados. 

Corrí 50 iteraciones en tu notebook cambiando esto, y parece no haber problema. Sugiero ampliar el rango de los priors, o iniciar la posición de beta y masa en otros valores como 3.1 y -19.5, por ejemplo.

**Comment by JoseSalvadorNeg** [comment]
Efectivamente, ese era el problema. Ya lo corregí y no parece haber problema. Muchas gracias

**Comment by alxogm** [comment]
@HiramHerrera también vio que tu Likelihood no es del todo correcto. Yo también vi que algunas definiciones no son correctas. Eso no interfiere con el issue que levantaste pero es muy probable que aunque ya empiece a correr bien, no llegará a la respuesta correcta. Entonces sugiero revises que el código está construyendo la matriz de covariance correctamente y que los parámetros se están variando bien también.

**Comment by JoseSalvadorNeg** [comment]
De acuerdo. Aprovechando el issue: ¿cuántas iteraciones de emcee serían suficientes para tener puntos suficientes para gráficar? De momento, con el likelihood tal cual como lo tengo en este instante, pude obtener unos valores para los parámetros a determinar (mal, obviamente) pero me topo con el problema de que la cantidad de puntos es muy poca, aún sin llevar a cabo el flattening de los datos.

**Comment by alxogm** [comment]
En realidad depende del problema el numero de iteraciones mínimas, pues depende de que se estén aceptando o no las propuestas. intenta con unos 5000 para 20 caminadores y a ver si ya tienes algo  ... puede ser que los problems de definición en el likelihood hagan que no se acepten los parámetros y por tanto necesites mas iteraciones para ver un buen contorno.

**Comment by JoseSalvadorNeg** [comment]
De acuerdo, tan pronto corrija el error del likelihood correré con esas especificaciones. Las definiciones que se me ocurren que están mal en comparación con el paper es el uso de reshape en lugar de una función para obtener la matriz compleja transpuesta (que me parece, es lo que se denota en el paper), pero no sé si ese sea el único error de definiciones. Por otro lado, no estoy seguro si me he equivocado a la hora de definir las sigmas necesarias para definir la matriz C.
